.Dd March 18, 2021
.Dt DEMO1 1
.Os
.Sh NAME
.Nm demo1
.Nd this is a demo cli installed with brew
.Sh SYNOPSIS
.Nm
.Op Fl optshere
.Sh DESCRIPTION
The
.Nm
demo cli is just a demo cli...
.Ar file
that is an underlined file
.Pq Sq \&-
that is a dash
.Nm
reads from the standard input.
If
.Ar file
is a
.Ux
domain socket,
.Nm
connects to it and then reads it until
.Dv EOF .
This complements the
.Ux
domain binding capability available in
.Xr inetd 8 .
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl b
Number the non-blank output lines, starting at 1 \&$
.Pq Ql \&$
at the end of each line.
.El
