#!/bin/bash

my_path=$0
. "$(dirname $my_path)/helpers.sh"

IFS=$'\n'

printf -v readme_path "%s/README.md" $(git_repo_root)

# Title / Header
content=($(just_wrap '#' ' ' $(git_repo_name)))
content+=("Executable projects written in various languages")
content+=("Find $(link_me Brew 'https://brew.sh/') install instructions at  $(link_me 'tatehanawalt/homebrew-devtools' 'https://github.com/tatehanawalt/homebrew-devtools')")
page_content+=($(html_wrap div 'align="center"' ${content[@]}))

repo_root="$(git_repo_root)"
printf "Repo Root: %s\n" "$repo_root"

project_names=$(find "$repo_root" \
  -maxdepth 1 \
  -mindepth 1 \
  -type d \
  -exec basename {} \; | \
  sed 's/^old.*//g' | \
  sed 's/\..*//' | \
  sort -u | \
  sed '/^$/d')

# Projects
page_content+=($(just_wrap '##' ' ' 'Overview'))

content=('Each project is a single project which can be built/compiled to a single binary (or java byte code) and installed/run with brew')
content+=('<br>')
content+=("$(just_wrap '**' '' 'Automation will be used as much as possible.') Even this README was autogenerated.")

content+=($(just_wrap '####' ' ' 'Projects Criteria:'))
content+=('<br>')
content+=($(just_wrap '**' '' 'Projects must have root level directories:'))
content+=('  - `bin`')
content+=('    - `build` - Executable file (described below) which builds the project')
content+=('  - `doc`')
content+=('    - `man`')
content+=('      - `<project_name>.1` - Man 1 Page file for the project')
page_content+=(${content[@]})

# Projects
page_content+=($(just_wrap '##' ' ' 'Projects'))
for name in ${project_names[@]}; do
  page_content+=($(link_me $name "https://github.com/tatehanawalt/$(git_repo_name)/tree/main/$name"))
done

printf "" > "$readme_path"
for row in "${page_content[@]}"; do
  printf "$row\n\n" >> "$readme_path"
done
