#!/usr/bin/env zsh

output_lines=(${(@f)"$(ls -l /usr/local/opt)"})

printf "\nDEV ENVIRONMENT:\n"
printf "\n"

printf "Keg: -> formula namespace (found in /usr/local/Cellar)\n"
printf "  - %s\n" $output_lines
printf "\n"

printf "FORMULA:\n"
printf "  - API REF:  https://rubydoc.brew.sh/Formula.html\n"
printf "  - COOKBOOK: https://docs.brew.sh/Formula-Cookbook\n"
printf "\n"

printf "WORKFLOWS:\n"
printf "  - EXAMPLES: https://github.com/actions/starter-workflows\n"
printf "  - ABOUT:    https://docs.github.com/en/actions/creating-actions/about-actions\n"
printf "\n"

printf "INFO:\n"
printf "  - eventually this will cover details on the env and instructions for testing the source code. right now its mostly just notes\n"
printf "\n"
